// ============================================================
// CONFIGURATION — Fill in your keys here
// ============================================================
// --- CONFIGURATION ---
const SUPABASE_URL = ""; // Replace with your Project URL
const SUPABASE_KEY = "";         // Replace with your 'Publishable key'

const OPENROUTER_KEY  = ""; // Your OpenRouter key (openrouter.ai)


function checkEmails() {
  var threads = GmailApp.getInboxThreads(0, 10);
  
  for (var i = 0; i < threads.length; i++) {
    var messages = threads[i].getMessages();
    var msg = messages[messages.length - 1];

    if (msg.isUnread()) {
      var emailData = {
        from_email: msg.getFrom(),
        subject:    msg.getSubject(),
        body:       msg.getPlainBody()
      };

      Logger.log("??????????????????????????????????????");
      Logger.log("?? New Email: " + emailData.subject);

      // 1. Save RAW email (to 'emails' table)
      postToSupabase("/rest/v1/emails", emailData);

      // 2. Get AI Analysis
      try {
        var aiData = analyzeWithOpenRouter(emailData.body);

        // 3. Save INTELLIGENCE (to 'briefings' table)
        var briefingData = {
          email_subject: emailData.subject,
          summary:       aiData.summary,
          tasks:         aiData.tasks,
          priority:      aiData.priority
        };
        postToSupabase("/rest/v1/briefings", briefingData);
        
        // 4. ? NEW: CREATE AUTO-REPLY DRAFT
        var draftBody = "Hello,\n\n" + 
                        "AI SUMMARY: " + aiData.summary + "\n\n" +
                        "ACTION ITEMS:\n- " + aiData.tasks.join("\n- ") + "\n\n" + 
                        "--- \nGenerated by FounderOS Agent";
        
        msg.getThread().createDraftReply(draftBody);
        Logger.log("?? Draft reply created in Gmail.");
        Logger.log("?? AI Summary: " + aiData.summary);

      } catch (err) {
        Logger.log("?? AI Error: " + err.message);
      }

      msg.markRead();
      Logger.log("? Done: " + emailData.subject);
      
      Utilities.sleep(2000);
    }
  }
}

// --- ?? OPENROUTER AI (Structured Output) ---
function analyzeWithOpenRouter(text) {
  var url = "https://openrouter.ai/api/v1/chat/completions";
  var prompt = "Analyze this email. Return ONLY a JSON object: " +
               "{\"summary\": \"1-sentence summary\", \"priority\": \"high|medium|low\", \"tasks\": [\"task1\", \"task2\"]}. " +
               "Email Content: " + text.substring(0, 3000);

  var payload = {
    model: "openrouter/auto",
    messages: [{ role: "user", content: prompt }]
  };

  var options = {
    method: "post",
    contentType: "application/json",
    headers: {
      "Authorization": "Bearer " + OPENROUTER_KEY,
      "HTTP-Referer": "https://script.google.com",
      "X-Title": "Founder Assistant"
    },
    payload: JSON.stringify(payload),
    muteHttpExceptions: true
  };

  var response = UrlFetchApp.fetch(url, options);
  var json = JSON.parse(response.getContentText());
  
  if (response.getResponseCode() === 200) {
    var aiText = json.choices[0].message.content;
    var cleanJson = aiText.replace(/```json|```/g, "").trim();
    return JSON.parse(cleanJson);
  } else {
    throw new Error("OpenRouter Error: " + response.getContentText());
  }
}

// --- ??? SUPABASE HELPER ---
function postToSupabase(endpoint, payload) {
  var url = SUPABASE_URL.replace(/\/$/, "") + endpoint;
  var options = {
    method: "post",
    contentType: "application/json",
    headers: {
      apikey: SUPABASE_KEY,
      Authorization: "Bearer " + SUPABASE_KEY,
      Prefer: "return=minimal"
    },
    payload: JSON.stringify(payload),
    muteHttpExceptions: true
  };
  
  var response = UrlFetchApp.fetch(url, options);
  if (response.getResponseCode() > 299) {
    Logger.log("? Database Error at " + endpoint + ": " + response.getContentText());
  } else {
    Logger.log("?? Saved to " + endpoint);
  }
}